## LAB ACTIVITY 13
## NAME : G S VITHUN; REG NO : 22MID0099; COURSE CODE: CSI3007; LAB : L27+L28;
## DATE : 12/09/2025

# TASK-4: Creating Numpy Arrays

## 1. array() method in numpy

In [4]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]) # Creating a 2-D Array
print(arr) 

[[1 2 3]
 [4 5 6]]


## 2. Attributes of numpy: size, shape, ndim

In [8]:
print(arr.size) # Displays the number of elements in a array

6


In [10]:
print(arr.shape) # Display the rows and columns

(2, 3)


In [12]:
print(arr.ndim) # Displays the dimension of array

2


## 3. reshape() method in numpy

In [14]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)
print("Original shape:", arr.shape)

Original array: [1 2 3 4 5 6]
Original shape: (6,)


In [17]:
# Reshape to a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3) # Reshape a 1-D array to 2-D array
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

[[1 2 3]
 [4 5 6]]
New shape: (2, 3)


## 4. arange() method in numpy

In [20]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  #Creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b #element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

numpysum(10) # function call

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [41]:
#ARRAY CREATION FUNCTIONS
import numpy as np
np.arange(10) # 0 TO BEFORE 10, Step Value 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(2, 10, dtype=float) # 2. to Before 10., step value 1.

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [47]:
np.arange(2, 3, 0.1) # 2 to Before 3, step value 0.1.

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

## 5. Array creation with different dimension using array() method from numpy module

In [25]:
#Creating Arrays from Sequences
#a list of numbers will create a 1D array,
a1D = np.array([1, 2, 3, 4])
print(a1D)

[1 2 3 4]


In [27]:
#a list of lists will create a 2D array
a2D = np.array([[1, 2], [3, 4]])
print(a2D)

[[1 2]
 [3 4]]


In [29]:
#further nested lists will create higher-dimensional arrays. 
#In general, any array object is called an ndarray in NumPy.
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 6. dtype attribute in numpy

In [32]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129])

| Name       | Alias(es)       | Size   | Range                           |
| ---------- | --------------- | ------ | ------------------------------- |
| `np.int8`  | `int8`          | 8-bit  | −128 to 127                     |
| `np.int16` | `int16`         | 16-bit | −32,768 to 32,767               |
| `np.int32` | `int32`, `int_` | 32-bit | −2,147,483,648 to 2,147,483,647 |
| `np.int64` | `int64`         | 64-bit | −9.2e18 to 9.2e18 (approx.)     |


In [37]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8)
# Error: OverflowError because the np.int8 data type cannot hold the values 128 and 129 (Here DeprecationWarning: based on python version)

C:\Users\sonal\AppData\Local\Temp\ipykernel_8540\1407719730.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)
C:\Users\sonal\AppData\Local\Temp\ipykernel_8540\1407719730.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

## 7. linspace() method in numpy

In [50]:
#numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 

#For example:
# np.linspace(start, stop, num)

# Start: 1.0

# Stop: 4.0

# num: 6 (number of samples including both endpoints)

# The interval is divided into 5 equal steps (because 6 points mean 5 intervals).
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

## 8. eye() method in numpy

In [53]:
#2D Array Creation functions 
#properties of special matrices represented as 2D arrays.
np.eye(3) # Identity matrice of 3X3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.eye(3, 5)   # Identity matrice of 3X5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [57]:
np.eye(3, 5, k=-2) #optional k argument
# When k is negative (e.g., k=-2), the diagonal shifts below the main diagonal
# when k is positive (e.g., k=1), the diagonal shifts above the main diagonal. 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [59]:
np.eye(3, 5, k=2) # Positive k argument

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 9. diag() method in numpy

In [74]:
# It returns an array containing the elements of the specified diagonal. 
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [82]:
# np.diag(v, k=1):
# When v is a 1D array, np.diag creates v 2D square matrix with a placed along the k-th diagonal.
# k=1 → the diagonal above the main (first superdiagonal).
# k=0 (default) extracts the main diagonal.
# k > 0 extracts diagonals above the main diagonal.
# k < 0 extracts diagonals below the main diagonal.

In [78]:
# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.
# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4
# Diagonal values are placed at positions: (0,1), (1,2), (2,3)
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [84]:
# numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
# It returns a 1D array that is only the diagonal elements. 

a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

## 10. Vandermonde Matrix

In [99]:
#np.vander(x, N) creates a Vandermonde matrix from a 1D input array x.

# [[x₁**(N-1), x₁**(N-2), ..., x₁**0],
#  [x₂**(N-1), x₂**(N-2), ..., x₂**0],
#  ...
#  [xₙ**(N-1), xₙ**(N-2), ..., xₙ**0]]

# So each row is a decreasing power of an element from x.

In [101]:
#np.linspace(0, 2, 5) → [0. , 0.5, 1. , 1.5, 2. ]
# N = 2 → two columns: x**1, x**0
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [109]:
np.vander([1, 2, 3, 4], 2) # creates 4X2 matrix
#Input: [1, 2, 3, 4]
# No of Columns 2

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

| x | x¹ | x⁰ |
| - | -- | -- |
| 1 | 1  | 1  |
| 2 | 2  | 1  |
| 3 | 3  | 1  |
| 4 | 4  | 1  |


In [113]:
np.vander((1, 2, 3, 4), 4) # creates 4X4 matrix
#N = 4 → columns: x**3, x**2, x**1, x**0
#Each row is [x**3, x**2, x, 1] for each x in the input.

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

| x | x³ | x² | x¹ | x⁰ |
| - | -- | -- | -- | -- |
| 1 | 1  | 1  | 1  | 1  |
| 2 | 8  | 4  | 2  | 1  |
| 3 | 27 | 9  | 3  | 1  |
| 4 | 64 | 16 | 4  | 1  |

| Code                                 | Shape    | Meaning                                           |
| ------------------------------------ | -------- | ------------------------------------------------- |
| `np.vander(np.linspace(0, 2, 5), 2)` | `(5, 2)` | 2-column Vandermonde matrix of `[0, 0.5, ..., 2]` |
| `np.vander([1, 2, 3, 4], 2)`         | `(4, 2)` | Powers: `[x, 1]` for each x                       |
| `np.vander((1, 2, 3, 4), 4)`         | `(4, 4)` | Powers: `[x**3, x**2, x, 1]`                      |


In [187]:
np.vander((1,2,3,4),3) # Each row is [x**2, x, 1] for each x in the input.

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

## 11. ones() method in numpy

In [119]:
#Creating a 1D array of size 5 filled with ones
arr1 = np.ones(5)  # shape=5 (1D), default dtype=float
print("1D Array of Ones:", arr1)

1D Array of Ones: [1. 1. 1. 1. 1.]


In [121]:
#Creating a 2D array (3 rows, 4 columns) filled with ones
arr2 = np.ones((3, 4))  # shape=(3,4) means 3x4 matrix
print("\n2D Array (3x4) of Ones:\n", arr2)


2D Array (3x4) of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [123]:
#Specifying data type as integer
arr3 = np.ones((2, 3), dtype=int)  # shape=(2,3), dtype=int
print("\n2D Integer Array (2x3) of Ones:\n", arr3)


2D Integer Array (2x3) of Ones:
 [[1 1 1]
 [1 1 1]]


In [125]:
#Creating a 3D array filled with ones
arr4 = np.ones((2, 2, 3))  # shape=(2,2,3) means 3D array (2 blocks, 2 rows, 3 columns)
print("\n3D Array of Ones:\n", arr4)


3D Array of Ones:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [127]:
#Creating a boolean array (True represents 1)
arr5 = np.ones((3, 3), dtype=bool)
print("\nBoolean Array (3x3) of Ones (True values):\n", arr5)


Boolean Array (3x3) of Ones (True values):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## 12. zeros() method in numpy

In [130]:
#Creating a 1D array of size 5 filled with zeros
arr1 = np.zeros(5)  # shape=5 (1D), default dtype=float
print("1D Array of Zeros:", arr1)

1D Array of Zeros: [0. 0. 0. 0. 0.]


In [132]:
#Creating a 2D array (3 rows, 4 columns) filled with zeros
arr2 = np.zeros((3, 4))  # shape=(3,4) means 3x4 matrix
print("\n2D Array (3x4) of Zeros:\n", arr2)


2D Array (3x4) of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [134]:
#Specifying data type as integer
arr3 = np.zeros((2, 3), dtype=int)  # shape=(2,3), dtype=int
print("\n2D Integer Array (2x3) of Zeros:\n", arr3)


2D Integer Array (2x3) of Zeros:
 [[0 0 0]
 [0 0 0]]


In [136]:
#Creating a 3D array filled with zeros
arr4 = np.zeros((2, 2, 3))  # shape=(2,2,3) means 3D array (2 blocks, 2 rows, 3 columns)
print("\n3D Array of Zeros:\n", arr4)


3D Array of Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [138]:
#Creating a boolean array (False represents 0)
arr5 = np.zeros((3, 3), dtype=bool)
print("\nBoolean Array (3x3) of Zeros (False values):\n", arr5)


Boolean Array (3x3) of Zeros (False values):
 [[False False False]
 [False False False]
 [False False False]]


## 13. indices() method in numpy

In [143]:
#Creating indices for a 2D array of shape (3, 3)
indices_2d = np.indices((3, 3))  # shape=(3,3) means 3 rows and 3 columns
print("Indices for a 3x3 grid:\n", indices_2d)

Indices for a 3x3 grid:
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [145]:
# indices_2d is actually a 3D array of shape (2, 3, 3):
# - The first 3x3 array contains row indices
# - The second 3x3 array contains column indices

In [147]:
print("\nRow indices (first array):\n", indices_2d[0])  # Row positions


Row indices (first array):
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


In [149]:
print("\nColumn indices (second array):\n", indices_2d[1])  # Column positions


Column indices (second array):
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


In [151]:
#Creating indices for a 2x4 array
indices_2x4 = np.indices((2, 4))  # shape=(2,4) means 2 rows, 4 columns

In [153]:
print("\nIndices for a 2x4 grid:\n", indices_2x4)


Indices for a 2x4 grid:
 [[[0 0 0 0]
  [1 1 1 1]]

 [[0 1 2 3]
  [0 1 2 3]]]


In [155]:
print("\nRow indices:\n", indices_2x4[0])


Row indices:
 [[0 0 0 0]
 [1 1 1 1]]


In [157]:
print("\nColumn indices:\n", indices_2x4[1])


Column indices:
 [[0 1 2 3]
 [0 1 2 3]]


## 14. random() method from random under numpy module

In [160]:
#Generate a single random float between 0 and 1
random_float = np.random.random()
print("Random Float (0 to 1):", random_float)

Random Float (0 to 1): 0.5670702501527762


In [162]:
#Generate a 1D array of 5 random floats between 0 and 1
random_array = np.random.random(5)
print("\n1D Array of Random Floats:", random_array)


1D Array of Random Floats: [0.88572119 0.47792031 0.22237558 0.23975361 0.16531422]


In [164]:
#Generate a 2D array (3x3) of random floats between 0 and 1
random_matrix = np.random.random((3, 3))
print("\n2D Array (3x3) of Random Floats:\n", random_matrix)


2D Array (3x3) of Random Floats:
 [[0.31060183 0.46810795 0.83945988]
 [0.15405996 0.64354632 0.30775679]
 [0.75405591 0.26768212 0.312058  ]]


In [166]:
#Generate random integers between 10 and 50 (5 numbers)
random_integers = np.random.randint(10, 50, size=5)
print("\nRandom Integers between 10 and 50:", random_integers)


Random Integers between 10 and 50: [18 44 21 32 40]


In [168]:
#Generate random numbers from a standard normal distribution (mean=0, std=1)
random_normal = np.random.randn(4)
print("\nRandom Numbers from Normal Distribution:", random_normal)


Random Numbers from Normal Distribution: [ 1.30968109  0.00161132 -1.0180968   0.78022295]


In [172]:
#Reproducibility - Set a random seed
np.random.seed(42)
print("\nRandom Numbers with Seed=42 (Reproducible):", np.random.random(3)) #Fix random number generator seed for reproducible results


Random Numbers with Seed=42 (Reproducible): [0.37454012 0.95071431 0.73199394]


## 15. Indexing and Slicing

In [175]:
#Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50, 60])
print("1D Array:", arr1d)

1D Array: [10 20 30 40 50 60]


In [177]:
print("\nIndexing on 1D Array:")
print("Element at index 0:", arr1d[0])   # First element
print("Element at index -1:", arr1d[-1]) # Last element (negative index)


Indexing on 1D Array:
Element at index 0: 10
Element at index -1: 60


In [179]:
print("\nSlicing on 1D Array:")
print("Elements from index 1 to 4:", arr1d[1:5])  # From index 1 up to 4
print("Every second element:", arr1d[::2])        # Step of 2
print("Reverse array:", arr1d[::-1])  


Slicing on 1D Array:
Elements from index 1 to 4: [20 30 40 50]
Every second element: [10 30 50]
Reverse array: [60 50 40 30 20 10]


In [181]:
#Create a 2D array (3x4 matrix)
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print("\n2D Array:\n", arr2d)


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [183]:
print("\nIndexing on 2D Array:")
print("Element at row 1, column 2:", arr2d[1, 2])   # 7 (row=1, col=2)
print("First row:", arr2d[0])                      # Whole first row
print("First column:", arr2d[:, 0])   


Indexing on 2D Array:
Element at row 1, column 2: 7
First row: [1 2 3 4]
First column: [1 5 9]


In [185]:
print("\nSlicing on 2D Array:")
print("Subarray (first 2 rows, columns 1 to 3):\n", arr2d[0:2, 1:3])
print("Last two rows:\n", arr2d[-2:, :])           # Last 2 rows
print("Every second column:\n", arr2d[:, ::2])     # All rows, step of 2 columns


Slicing on 2D Array:
Subarray (first 2 rows, columns 1 to 3):
 [[2 3]
 [6 7]]
Last two rows:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
Every second column:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]
